### ISSUE TITLE
Cannot expand multiple occurrences of macroname

### ISSUE THREAD

**Issue by JocaPC** [ParksProjets/C-Preprocessor#11]
I have created simple macro-definition `#define PI 3.14` and I'm trying to process text with two occurrence of `PI`. Only the first one is processed.

Code:
```
var compiler = require("c-preprocessor");

compiler.compile("#define PI 3.14\nprint PI and PI", {}, function(err, result){
    console.log(result);
})
```
Result:
> node index.js
>print 3.14 and PI

```
var compiler = require("c-preprocessor");

compiler.compile("print PI, PI, PI", {constants: {"PI":"3.14"}}, function(err, result){
    console.log(result);
})
```

Result:
> node index.js
> print 3.14, PI, PI

**Comment by ParksProjets** [comment]
Fixed in version 0.2.13.
Thanks for reporting!
