### ISSUE TITLE
Macros with 4 parameters

### ISSUE THREAD

**Issue by ttoinou** [ParksProjets/C-Preprocessor#2]
Input file.glsl : 
```
#define PACK4(A,B,C,D) (A+B+C+D)
#define p1(A,B,C,D) (PACK4(A,B,C,D))
```

Error 

> (line 2 in "file.glsl") too few arguments for macro PACK4

**Comment by ParksProjets** [comment]
Hi.
I fix this issue, in the version 0.2.8.
Thanks for reporting.
