### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by futurist** [ParksProjets/C-Preprocessor#3]
When `npm i -g c-preprocessor`

Then `c-preprocessor abc.js`

Throw error below:

```
env: node\r: No such file or directory
```

macOS 10.11.6

Node 6.1.0

**Comment by ParksProjets** [comment]
Hi !
I fixed this issue in the version 0.2.10.
The problem was the newline characters in the file **global.js**.
Thanks for reporting.
