### ISSUE TITLE
Add support and/or documentation for __LINE__ and __FILE__ macros

### ISSUE THREAD

**Issue by mnebuerquo** [ParksProjets/C-Preprocessor#7]
Maybe this is a documentation issue rather than a missing feature, but I was looking for these to help with implementing a logging module.

See this doc on standard predefined C macros:
https://gcc.gnu.org/onlinedocs/cpp/Standard-Predefined-Macros.html

The __FILE__ and __LINE__ macros could fill a void in javascript, since it is extremely difficult to get original source filenames and line numbers when transpiling, bundling, or minifying code.

**Comment by ParksProjets** [comment]
Hi!
`__LINE__` and `__FILE__` constants were implemented but not documented. I added them to the README.
Thanks for reporting.
