### ISSUE TITLE
Crashes after exhausting heap (Doesn't handle marco's with no arguments)

### ISSUE THREAD

**Issue by JamesBewley** [ParksProjets/C-Preprocessor#9]
I have a file with 18562 lines and unfortunately the c-preprocessor runs out of RAM with a heap allocation error.

I've pushed the limit up to 12GB with the following but it still just consumes the heap and dies.

`export NODE_OPTIONS="--max-old-space-size=12288"`

I'm using node v12.13.0

`node/v12.13.0/lib/node_modules/c-preprocessor/lib/compiler.js:~427]`

**Comment by JamesBewley** [comment]
I found the problem; it was because c-preprocessor couldn't handle marcos without arguments (GCC just treats this as a constant).

A quick hack in _compiler.js_ got it working for me

`447: if(end >i1) args.push(text.substring(i1, end));`

**Comment by ParksProjets** [comment]
Fixed in version 0.2.13.
Thanks for reporting!
